### ISSUE TITLE
Implementar interfaz de reportes

### ISSUE THREAD

**Issue by ypicoleal** [exildev/Exile#3]
En esta interface se implementaran el envío de nuevos reportes y el listado de mis reportes con el estado actual del mismo

- [x] Pantalla de agregar reportes
- [x] Pantalla de listar reportes

**Comment by ypicoleal** [comment]
un reporte tiene nombre, descripción, archivos de fotos, lugar*, cliente* y un tipo de reporte*

*estos campos son opcionales

**Comment by mariobp** [comment]
Url de lista de reportes: /novedades/reporte/list/?page=1

- Ejemplo del json:

{"count": 1, "page_range": "xrange(1, 2)", "num_rows": 1, "num_pages": 1, "object_list": [{"latitud": null, "servicios": {"edit": "/novedades/reporte/form/2/", "add": "/novedades/reporte/form/", "delete": "/novedades/reporte/delete/2/"}, "fecha": "06/06/2017 11:42PM", "numero": null, "tipoR": {"nombre": "Informativo", "id": 1}, "clienteR": {"nombre": "Mario José Barrios Pacheco", "id": 1}, "descripcion": "demo 2", "nombre": "Demo", "creatorR": {"username": "asistente1", "nombre": "Lolo Juju"}, "lugarR": {"nombre": "Sede Exile", "id": 2}, "estado": false, "id": 2, "longitud": null}]}

**Comment by mariobp** [comment]
Los servicios que necesitas para poder llenar un formulario de reporte son los siguientes:

- Tipo:
/novedades/tipo/list/

{"count": 1, "page_range": "xrange(1, 2)", "num_rows": 1, "num_pages": 1, "object_list": [{"nombre": "Informativo", "servicios": {"edit": "/novedades/tipo/form/1/", "add": "/novedades/tipo/form/", "delete": "/novedades/tipo/delete/1/"}, "id": 1}]}

- Cliente:
/operacion/cliente/list/

{"count": 1, "page_range": "xrange(1, 2)", "num_rows": 1, "num_pages": 1, "object_list": [{"servicios": {"edit": "/operacion/cliente/form/1/", "add": "/operacion/cliente/form/", "delete": "/operacion/cliente/delete/1/"}, "tipoI": {"nombre": "Identificación", "id": 1}, "direccion": "Chile Mz. 2 Lt. 4", "identificacion": "1143361361", "nombre": "Mario José Barrios Pacheco", "telefono": "3156899783", "id": 1}]}

- Lugar
/operacion/lugar/list/
{"count": 1, "page_range": "xrange(1, 2)", "num_rows": 1, "num_pages": 1, "object_list": [{"latitud": null, "servicios": {"edit": "/operacion/lugar/form/2/", "add": "/operacion/lugar/form/", "delete": "/operacion/lugar/delete/2/"}, "eliminado": false, "nombre": "Sede Exile", "direccion": "Centro", "id": 2, "longitud": null}]}

Nota: ninguno de estos campos es obligatorio en el reporte

**Comment by mariobp** [comment]
url para agregar /novedades/reporte/form/
